# Generated by Django 2.1.7 on 2019-07-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raindata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=250)),
                ('rainfall', models.FloatField()),
                ('evaporation', models.FloatField()),
            ],
        ),
    ]
